import type { CapabilityCoverageItem } from "../models/CapabilityCoverage";

export const capabilityRegistry: CapabilityCoverageItem[] = [
  { id: "process-intelligence", name: "Business Process Intelligence", category: "BUSINESS", status: "FOUNDATION", purpose: "BPMN/process discovery/conformance", backendModule: "process_mining" },
  { id: "enterprise-architecture", name: "Enterprise Architecture Intelligence", category: "ARCHITECTURE", status: "FOUNDATION", purpose: "Business/application/data/technology architecture", backendModule: "enterprise_graph" },
  { id: "reverse-engineering", name: "Reverse Engineering", category: "ARCHITECTURE", status: "FOUNDATION", purpose: "Code/database/configuration to architecture and logic", backendModule: "code_intelligence" },
  { id: "business-rule-mining", name: "Business Rule Mining", category: "BUSINESS", status: "FOUNDATION", purpose: "Recover rules from documents, SQL, code and workflows", backendModule: "rule_mining" },
  { id: "knowledge-graph", name: "Persistent Enterprise Knowledge Graph", category: "PLATFORM", status: "FOUNDATION", purpose: "Unified entities, relationships, rules, defects, twins and evidence", backendModule: "knowledge_graph" },
  { id: "metadata-lineage", name: "Metadata + Data Lineage", category: "DATA", status: "FOUNDATION", purpose: "Source to transformation to target traceability", backendModule: "knowledge_graph" },
  { id: "data-contracts", name: "Data Contracts", category: "DATA", status: "FOUNDATION", purpose: "Schema, ownership, quality, SLA and compatibility", backendModule: "data_contracts" },
  { id: "data-observability", name: "Data Observability", category: "DATA", status: "FOUNDATION", purpose: "Freshness, volume, schema, distribution and drift", backendModule: "observability" },
  { id: "mdm-entity-resolution", name: "MDM + Entity Resolution", category: "DATA", status: "FOUNDATION", purpose: "Resolve enterprise master/reference conflicts and duplicates", backendModule: "entity_resolution" },
  { id: "privacy", name: "Privacy Engineering + Masking", category: "SECURITY", status: "GOVERNED", purpose: "PII classification, masking, tokenization and synthetic data", backendModule: "privacy_engine" },
  { id: "api-intelligence", name: "API Intelligence", category: "INTEGRATION", status: "ADAPTER_REQUIRED", purpose: "REST, SOAP, GraphQL, gRPC, OData and contracts", backendModule: "deep_discovery" },
  { id: "event-cdc", name: "Event + CDC Intelligence", category: "INTEGRATION", status: "ADAPTER_REQUIRED", purpose: "Kafka/MQ/events/log-based CDC, ordering and replay", backendModule: "deep_discovery" },
  { id: "distributed-systems", name: "Distributed Systems Intelligence", category: "ARCHITECTURE", status: "FOUNDATION", purpose: "Replication, consistency, retries, idempotency and failure modes", backendModule: "enterprise_graph" },
  { id: "mainframe", name: "Mainframe / Legacy Modernization", category: "ARCHITECTURE", status: "ADAPTER_REQUIRED", purpose: "COBOL, JCL, VSAM, CICS, DB2 and 4GL", backendModule: "code_intelligence" },
  { id: "database-intelligence", name: "Database Reverse Engineering", category: "DATA", status: "ADAPTER_REQUIRED", purpose: "Schemas, indexes, constraints, procedures, jobs and dependencies", backendModule: "deep_discovery" },
  { id: "warehouse-lakehouse", name: "Warehouse / Lakehouse Intelligence", category: "DATA", status: "FOUNDATION", purpose: "Dimensional, Data Vault, semantic metrics and lakehouse", backendModule: "enterprise_graph" },
  { id: "document-multimodal", name: "Document + Multimodal Intelligence", category: "AI", status: "ADAPTER_REQUIRED", purpose: "PDF, Office, diagrams, images, scans, audio/video evidence", backendModule: "document_intelligence" },
  { id: "rag-memory", name: "RAG + Persistent AI Memory", category: "AI", status: "FOUNDATION", purpose: "Evidence-grounded retrieval and project memory", backendModule: "knowledge_graph" },
  { id: "ai-evaluation", name: "AI Evaluation + Explainability", category: "AI", status: "FOUNDATION", purpose: "Accuracy, grounding, confidence and agent performance", backendModule: "agent_runtime" },
  { id: "ai-security", name: "AI Security + Governance", category: "SECURITY", status: "GOVERNED", purpose: "Prompt injection, knowledge poisoning and tool authorization", backendModule: "policy_engine" },
  { id: "optimization", name: "Optimization + Constraint Solving", category: "AI", status: "FOUNDATION", purpose: "Wave planning, scheduling, resources, cost and downtime", backendModule: "optimization_engine" },
  { id: "causal-probabilistic", name: "Causal + Probabilistic AI", category: "AI", status: "FOUNDATION", purpose: "Evidence-ranked root cause and uncertainty reasoning", backendModule: "causal_engine" },
  { id: "cloud-k8s-iac", name: "Cloud + Kubernetes + IaC Intelligence", category: "PLATFORM", status: "ADAPTER_REQUIRED", purpose: "AWS, Azure, GCP, Kubernetes, Terraform and deployment topology", backendModule: "deep_discovery" },
  { id: "finops", name: "FinOps", category: "OPERATIONS", status: "FOUNDATION", purpose: "Migration and target operating-cost optimization", backendModule: "optimization_engine" },
  { id: "aiops-sre", name: "Observability + AIOps + SRE", category: "OPERATIONS", status: "ADAPTER_REQUIRED", purpose: "Logs, metrics, traces, incidents, SLOs and remediation", backendModule: "observability" },
  { id: "resilience", name: "Chaos + DR + Business Continuity", category: "OPERATIONS", status: "GOVERNED", purpose: "Failure rehearsal, failover and continuity validation", backendModule: "simulation_engine" },
  { id: "compliance", name: "Compliance + Policy-as-Code", category: "SECURITY", status: "GOVERNED", purpose: "Machine-checkable enterprise/regulatory policy controls", backendModule: "policy_engine" },
  { id: "protocols", name: "Industry Interoperability Protocols", category: "INTEROPERABILITY", status: "FOUNDATION", purpose: "ISO 20022/8583, HL7/FHIR/DICOM, OPC UA/Modbus, X12/EDIFACT", backendModule: "protocol_registry" },
  { id: "pqc", name: "Post-Quantum Cryptography Readiness", category: "SECURITY", status: "FOUNDATION", purpose: "Identify cryptographic dependencies and future migration needs", backendModule: "policy_engine" },
  { id: "decision-intelligence", name: "Decision Intelligence", category: "AI", status: "FOUNDATION", purpose: "Evidence, objective, constraints, alternatives, risk, cost and outcome", backendModule: "causal_engine" },
  { id: "digital-twin-runtime", name: "Persistent Digital Twin + Simulation Runtime", category: "PLATFORM", status: "FOUNDATION", purpose: "State/version/twin quality/scenarios/target preview", backendModule: "twin_store" },
  { id: "dynamic-agent-runtime", name: "Dynamic Agent Runtime", category: "AI", status: "FOUNDATION", purpose: "Runtime specialist creation, assignment, evaluation and evidence", backendModule: "agent_runtime" },
];

