export type ClientDemoScenario = {
  id: string;
  name: string;
  industry: string;
  executiveTheme: string;
  clientProfile: string;
  primaryOutcome: string;
  systems: string[];
  processes: string[];
  risks: string[];
  kpis: Array<{
    label: string;
    before: string;
    after: string;
    note: string;
  }>;
  specialistAgents: string[];
  digitalTwinFocus: string[];
  demoNarrative: string[];
  safetyStatement: string;
};

export const clientDemoScenarios: ClientDemoScenario[] = [
  {
    id: "banking-modernization",
    name: "Global Banking Modernization",
    industry: "Banking & Financial Services",
    executiveTheme: "Modernize a regulated banking estate without losing control.",
    clientProfile:
      "Large multi-country bank with mainframe, Oracle, payments, CRM, risk and regulatory reporting platforms.",
    primaryOutcome:
      "Create a governed modernization path across customer, payments, data and compliance dependencies.",
    systems: [
      "Core Banking Mainframe",
      "Oracle Customer Database",
      "Payments Hub",
      "Salesforce CRM",
      "AML/KYC Platform",
      "Regulatory Data Warehouse",
      "Kafka Integration Layer",
      "Kubernetes Services",
    ],
    processes: [
      "Customer onboarding",
      "KYC/AML",
      "Payments",
      "Credit decisioning",
      "Regulatory reporting",
      "Record-to-report",
    ],
    risks: [
      "Customer-data inconsistency",
      "Payment interruption",
      "Regulatory evidence gaps",
      "Schema drift",
      "Unauthorized production change",
    ],
    kpis: [
      { label: "Estate visibility", before: "Fragmented", after: "Connected", note: "Digital Twin context" },
      { label: "Migration assurance", before: "Manual", after: "Continuous", note: "Validation + reconciliation" },
      { label: "Production authority", before: "Distributed", after: "Governed", note: "Explicit approval gates" },
      { label: "Audit evidence", before: "Collected later", after: "Generated by lifecycle", note: "Evidence chain" },
    ],
    specialistAgents: ["KDOM", "KDATA", "KAPP", "KSEC", "KMIG", "KQA", "KEVD"],
    digitalTwinFocus: ["Customers", "Payments", "APIs", "Databases", "Controls", "Evidence"],
    demoNarrative: [
      "Infer banking and enterprise-function context.",
      "Map customer, payment and regulatory dependencies.",
      "Simulate modernization impact before execution.",
      "Validate a governed DEV migration path.",
      "Reconcile outcomes and generate evidence.",
    ],
    safetyStatement:
      "Reference demonstration only: production writes, cutover, destructive actions and policy bypass remain denied.",
  },
  {
    id: "insurance-core-transformation",
    name: "Insurance Core Platform Transformation",
    industry: "Insurance",
    executiveTheme: "Transform policy and claims platforms with traceable assurance.",
    clientProfile:
      "Composite insurer modernizing policy administration, claims, underwriting and customer platforms.",
    primaryOutcome:
      "Reduce migration risk while preserving policy, claims and regulatory business rules.",
    systems: [
      "Policy Administration",
      "Claims Platform",
      "Underwriting Engine",
      "Billing",
      "CRM",
      "Document Management",
      "Data Lake",
      "API Gateway",
    ],
    processes: ["Quote-to-bind", "Claims intake", "Underwriting", "Renewals", "Billing", "Compliance reporting"],
    risks: ["Policy-rule loss", "Claims-data defects", "Document mismatch", "Integration regression", "Approval bypass"],
    kpis: [
      { label: "Rule traceability", before: "Siloed", after: "Linked", note: "Rules + evidence" },
      { label: "Regression coverage", before: "Reactive", after: "Automated", note: "KQA assurance" },
      { label: "Change impact", before: "Manual", after: "Graph-based", note: "Digital Twin blast radius" },
      { label: "Migration proof", before: "Sampled", after: "Reconciled", note: "Source-target evidence" },
    ],
    specialistAgents: ["KDOM", "KPROC", "KDATA", "KDEF", "KMIG", "KQA", "KEVD"],
    digitalTwinFocus: ["Policies", "Claims", "Rules", "Documents", "APIs", "Controls"],
    demoNarrative: [
      "Understand insurance products and operating functions.",
      "Mine policy and claims rules.",
      "Analyze downstream claim and billing impact.",
      "Run governed migration assurance.",
      "Produce reconciliation and evidence.",
    ],
    safetyStatement:
      "Reference demonstration only: no production insurance transaction is executed.",
  },
  {
    id: "telecom-bss-oss",
    name: "Telecom BSS/OSS Modernization",
    industry: "Telecommunications",
    executiveTheme: "Control high-volume modernization across customer, billing and network domains.",
    clientProfile:
      "National telecom operator with CRM, billing, order management, network inventory and API integration estates.",
    primaryOutcome:
      "Coordinate BSS/OSS modernization while exposing cross-domain dependencies and release risk.",
    systems: ["CRM", "Billing", "Order Management", "Network Inventory", "Provisioning", "API Gateway", "Event Bus", "Data Platform"],
    processes: ["Lead-to-order", "Order-to-activate", "Usage-to-bill", "Trouble-to-resolve", "Network change", "Revenue assurance"],
    risks: ["Billing leakage", "Activation failures", "API dependency break", "Network-service mismatch", "Release regression"],
    kpis: [
      { label: "Dependency visibility", before: "Partial", after: "End-to-end", note: "BSS/OSS Digital Twin" },
      { label: "Release assurance", before: "Batch", after: "Continuous", note: "Automated QA" },
      { label: "RCA", before: "Cross-team", after: "Graph-assisted", note: "Causal analysis" },
      { label: "Evidence", before: "Manual", after: "Lifecycle-linked", note: "Audit trail" },
    ],
    specialistAgents: ["KDOM", "KPROC", "KAPP", "KDEF", "KSRE", "KQA", "KEVD"],
    digitalTwinFocus: ["Customers", "Orders", "Billing", "Network", "APIs", "Incidents"],
    demoNarrative: [
      "Understand BSS/OSS domains and customer journeys.",
      "Map service-order-network dependencies.",
      "Diagnose a cross-system failure.",
      "Simulate release blast radius.",
      "Validate and evidence the modernization path.",
    ],
    safetyStatement:
      "Reference demonstration only: no network or production billing action is authorized.",
  },
  {
    id: "healthcare-platform",
    name: "Healthcare Data & Platform Modernization",
    industry: "Healthcare & Life Sciences",
    executiveTheme: "Modernize sensitive healthcare platforms with privacy and evidence controls.",
    clientProfile:
      "Healthcare provider integrating EHR, patient, scheduling, billing, laboratory and analytics systems.",
    primaryOutcome:
      "Improve interoperability and migration assurance while preserving patient-data governance.",
    systems: ["EHR", "Patient Administration", "Scheduling", "Billing", "Laboratory", "Imaging", "Integration Engine", "Analytics Platform"],
    processes: ["Patient registration", "Appointment", "Clinical order", "Result reporting", "Billing", "Data exchange"],
    risks: ["Patient identity mismatch", "Privacy exposure", "Interface failure", "Clinical data loss", "Incomplete audit evidence"],
    kpis: [
      { label: "Patient identity", before: "Duplicated", after: "Resolved", note: "Entity resolution" },
      { label: "Privacy visibility", before: "Manual", after: "Classified", note: "Privacy assessment" },
      { label: "Interface assurance", before: "Point testing", after: "Dependency-aware", note: "Digital Twin" },
      { label: "Evidence", before: "Post-hoc", after: "Continuous", note: "Lifecycle evidence" },
    ],
    specialistAgents: ["KDOM", "KDATA", "KSEC", "KAPP", "KMIG", "KQA", "KEVD"],
    digitalTwinFocus: ["Patients", "Clinical Data", "Interfaces", "Privacy", "Applications", "Evidence"],
    demoNarrative: [
      "Infer healthcare and data-governance context.",
      "Classify sensitive data and resolve entities.",
      "Map clinical and operational dependencies.",
      "Simulate platform migration impact.",
      "Reconcile and evidence the target state.",
    ],
    safetyStatement:
      "Reference demonstration only: no clinical or production patient action is executed.",
  },
  {
    id: "manufacturing-digital-core",
    name: "Manufacturing Digital Core Transformation",
    industry: "Manufacturing",
    executiveTheme: "Connect ERP, plant and supply-chain transformation through one Digital Twin.",
    clientProfile:
      "Global manufacturer modernizing ERP, MES, warehouse, supply-chain and plant integration platforms.",
    primaryOutcome:
      "Expose operational dependencies and assure transformation without disrupting production.",
    systems: ["SAP ERP", "MES", "Warehouse Management", "PLM", "SCADA Integration", "Supply Chain Planning", "Data Platform", "IoT Gateway"],
    processes: ["Plan-to-produce", "Procure-to-pay", "Order-to-cash", "Quality management", "Maintenance", "Warehouse fulfillment"],
    risks: ["Production disruption", "Master-data mismatch", "Interface latency", "Inventory variance", "Quality-rule regression"],
    kpis: [
      { label: "Plant dependency map", before: "Static", after: "Connected", note: "Digital Twin" },
      { label: "Master-data assurance", before: "Manual", after: "Reconciled", note: "Source-target validation" },
      { label: "Change impact", before: "Workshop", after: "Simulated", note: "Blast radius" },
      { label: "Release confidence", before: "Late", after: "Continuous", note: "KQA" },
    ],
    specialistAgents: ["KDOM", "KPROC", "KDATA", "KAPP", "KSRE", "KQA", "KEVD"],
    digitalTwinFocus: ["ERP", "MES", "Plants", "Materials", "Interfaces", "Quality"],
    demoNarrative: [
      "Understand manufacturing processes and technology estate.",
      "Map ERP-MES-supply-chain dependencies.",
      "Simulate plant-impact scenarios.",
      "Run governed transformation assurance.",
      "Reconcile operational data and evidence.",
    ],
    safetyStatement:
      "Reference demonstration only: no plant, equipment or production control action is executed.",
  },
  {
    id: "government-modernization",
    name: "Government Legacy Modernization",
    industry: "Government / Public Sector",
    executiveTheme: "Modernize public-service platforms with strong governance and evidence.",
    clientProfile:
      "Large public-sector organization replacing legacy citizen, case, finance and document-management systems.",
    primaryOutcome:
      "Create a transparent modernization path with explicit approval, privacy and audit controls.",
    systems: ["Citizen Services", "Case Management", "Finance", "Identity", "Document Management", "Integration Platform", "Data Warehouse", "Legacy Mainframe"],
    processes: ["Citizen onboarding", "Case processing", "Benefits assessment", "Payment", "Records management", "Audit reporting"],
    risks: ["Citizen-data mismatch", "Case-rule loss", "Privacy breach", "Audit gaps", "Legacy dependency failure"],
    kpis: [
      { label: "Legacy visibility", before: "Fragmented", after: "Mapped", note: "Discovery + Digital Twin" },
      { label: "Approval governance", before: "Distributed", after: "Explicit", note: "Authoritative gates" },
      { label: "Migration evidence", before: "Manual", after: "Linked", note: "Evidence lifecycle" },
      { label: "Service continuity", before: "Assumed", after: "Simulated", note: "Impact analysis" },
    ],
    specialistAgents: ["KDOM", "KPROC", "KDATA", "KSEC", "KMIG", "KQA", "KEVD"],
    digitalTwinFocus: ["Citizens", "Cases", "Rules", "Documents", "Legacy Systems", "Controls"],
    demoNarrative: [
      "Understand public-service context and controls.",
      "Discover legacy applications and dependencies.",
      "Trace privacy and case-processing risks.",
      "Simulate modernization changes.",
      "Validate, reconcile and evidence the outcome.",
    ],
    safetyStatement:
      "Reference demonstration only: no citizen-facing production action is executed.",
  },
];

export const defaultClientDemoScenario = clientDemoScenarios[0];

