from __future__ import annotations

ORACLE_ADVANCED_TOPICS = [
    {"area":"Oracle AI Database","name":"Oracle AI Database 26ai","capabilities":["architecture","installation","administration","multitenant","CDB/PDB","upgrades","migration","performance"]},
    {"area":"Oracle AI","name":"AI Vector Search","capabilities":["VECTOR datatype","embeddings","vector indexes","similarity search","hybrid search","RAG"]},
    {"area":"Oracle AI","name":"Select AI","capabilities":["natural language to SQL","conversational querying","AI profiles","LLM integration"]},
    {"area":"Oracle AI","name":"Select AI Agent","capabilities":["agent database interaction","tools","reasoning","enterprise data access"]},
    {"area":"Oracle AI","name":"Private Agent Factory","capabilities":["private agents","agent creation","orchestration","governance","database grounding"]},
    {"area":"Oracle AI","name":"Agentic AI + Oracle DB","capabilities":["multi-agent workflows","tool calling","database tools","approvals","policies","guardrails"]},
    {"area":"Oracle AI","name":"Private AI Services","capabilities":["private LLM deployment","secure enterprise AI","model serving","controlled data access"]},
    {"area":"Oracle AI","name":"RAG with Oracle","capabilities":["chunking","embeddings","retrieval","reranking","prompt construction","grounding","citations"]},
    {"area":"Oracle ML","name":"Oracle Machine Learning","capabilities":["in-database ML","AutoML","Python integration","model deployment","scoring"]},
    {"area":"Oracle Data","name":"Graph Analytics","capabilities":["property graph","SQL property graph","traversal","relationship analysis","Graph AI"]},
    {"area":"Oracle Data","name":"JSON Relational Duality","capabilities":["JSON relational mapping","duality views","document relational development"]},
    {"area":"Oracle SQL","name":"Modern SQL","capabilities":["analytics","SQL macros","pattern matching","recursive SQL","JSON SQL","graph SQL"]},
    {"area":"Oracle SQL","name":"SQL Assertions","capabilities":["multi-table business rules","integrity enforcement"]},
    {"area":"Oracle PL/SQL","name":"Advanced PL/SQL","capabilities":["packages","procedures","functions","collections","bulk processing","dynamic SQL","instrumentation","secure coding"]},
    {"area":"Oracle Architecture","name":"Microservices Database Patterns","capabilities":["sagas","events","outbox","service-owned data","distributed transactions"]},
    {"area":"Oracle Resilience","name":"Oracle RAC","capabilities":["clustering","Cache Fusion","services","load balancing","high availability"]},
    {"area":"Oracle Resilience","name":"Data Guard","capabilities":["standby","Active Data Guard","switchover","failover","disaster recovery"]},
    {"area":"Oracle Integration","name":"GoldenGate","capabilities":["replication","CDC","active-active","heterogeneous migration","streaming"]},
    {"area":"Oracle Migration","name":"Zero Downtime Migration","capabilities":["online database migration","cloud migration","reduced cutover"]},
    {"area":"Oracle Cloud","name":"OCI Database Services","capabilities":["Base Database","Exadata Database Service","Autonomous Database"]},
    {"area":"Oracle Cloud","name":"Oracle Cloud Infrastructure","capabilities":["compute","networking","storage","IAM","database","Kubernetes","observability","security"]},
    {"area":"Oracle Security","name":"Oracle Database Security","capabilities":["TDE","Database Vault","Data Safe","auditing","masking","privilege management","encryption"]},
    {"area":"Oracle Performance","name":"Performance Tuning","capabilities":["AWR","ASH","ADDM","SQL Monitor","execution plans","indexes","partitioning","optimizer"]},
    {"area":"Oracle Events","name":"Advanced Queuing / Transactional Event Queues","capabilities":["event-driven architecture","messaging","database event streams"]},
    {"area":"Oracle Integration","name":"REST Data Services - ORDS","capabilities":["REST APIs","REST-enabled SQL","database application APIs"]},
    {"area":"Oracle Apps","name":"APEX","capabilities":["low-code applications","AI-assisted development","database-centric apps"]},
    {"area":"Oracle Integration","name":"Oracle Integration Cloud","capabilities":["application integration","APIs","SaaS integration","events","process automation"]},
    {"area":"Oracle Data Integration","name":"Oracle Data Integrator","capabilities":["ELT","mappings","Knowledge Modules","CDC","enterprise data integration"]},
    {"area":"Oracle Analytics","name":"Oracle Analytics Cloud","capabilities":["semantic models","dashboards","AI analytics","self-service BI"]},
    {"area":"Oracle Fusion","name":"Oracle Fusion Cloud ERP","capabilities":["Financials","Procurement","Projects","Risk Management","Enterprise Performance"]},
    {"area":"Oracle Fusion","name":"Fusion HCM","capabilities":["Core HR","payroll","talent","recruitment","workforce management"]},
    {"area":"Oracle Fusion","name":"Fusion SCM","capabilities":["inventory","procurement","manufacturing","order management","logistics"]},
    {"area":"Oracle Fusion","name":"Oracle AI Agent Studio","capabilities":["build agents","connect agents","run agents","Fusion integration"]},
    {"area":"Oracle EBS","name":"Oracle EBS R12.2","capabilities":["Financials","SCM","HRMS","Order Management","iStore","workflows","APIs","extensions"]},
    {"area":"Oracle Modernization","name":"EBS to Fusion Migration","capabilities":["discovery","fit-gap","data conversion","integrations","extensions","testing","cutover"]},
    {"area":"Oracle Modernization","name":"Oracle Forms Modernization","capabilities":["Forms assessment","Reports assessment","REST conversion","APEX modernization","Java modernization"]},
    {"area":"Oracle Migration","name":"Oracle Data Migration","capabilities":["assessment","discovery","profiling","mapping","cleansing","transformation","load","reconciliation"]},
    {"area":"Oracle Data","name":"Data Quality","capabilities":["profiling","validation","standardization","deduplication","survivorship","reconciliation"]},
    {"area":"Oracle Data","name":"Master Data Management","capabilities":["customer","supplier","product","reference data governance"]},
    {"area":"Oracle Data","name":"Metadata Management","capabilities":["schemas","lineage","catalog","dependencies","impact analysis"]},
    {"area":"Oracle DevOps","name":"DevOps for Oracle","capabilities":["Git","CI/CD","Liquibase","database change management","automation"]},
    {"area":"Oracle Cloud","name":"Terraform + OCI","capabilities":["infrastructure as code","database provisioning","cloud provisioning"]},
    {"area":"Oracle Cloud","name":"Kubernetes + Oracle","capabilities":["containerized applications","operators","microservices","cloud-native integration"]},
    {"area":"Oracle Operations","name":"Observability","capabilities":["monitoring","logs","metrics","tracing","performance diagnostics"]},
    {"area":"Oracle Governance","name":"Enterprise AI Governance","capabilities":["model governance","agent permissions","data security","auditability","human approvals","explainability"]},
]
