import React, {useMemo, useState} from "react";
import type {KmitoraUiAdapter, ReadinessSummary, RequirementDraft, RequirementUnderstanding, SystemSummary} from "./types";
import "./kmitora-enterprise-os.css";

type Props={source:SystemSummary;target:SystemSummary;understanding?:RequirementUnderstanding;readiness?:Partial<ReadinessSummary>;adapter?:KmitoraUiAdapter};

function SystemCard({label,system,onConnect,onView,onUnderstand}:{label:"SOURCE"|"TARGET";system:SystemSummary;onConnect?:()=>void;onView?:()=>void;onUnderstand?:()=>void}){
 const connected=system.status==="connected"; const pct=Math.max(0,Math.min(100,system.understandingPercent??0));
 const metrics=Object.entries(system.counts??{});
 return <section className="ko-card ko-system">
   <div className="ko-head"><div><span className="ko-eye">{label} SYSTEM</span><h2>{connected?system.name:`Connect your ${label.toLowerCase()} system`}</h2></div><span className={`ko-pill ${connected?"ok":""}`}>{connected?"● Connected":"○ Not connected"}</span></div>
   {!connected?<div className="ko-empty"><p>KMITORA will automatically discover structure, dependencies, business logic, processes and operational context.</p><button className="ko-primary" onClick={onConnect}>+ Connect {label==="SOURCE"?"Source":"Target"}</button></div>:
   <><div className="ko-metrics">{metrics.map(([k,v])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div>
   <div className="ko-progressBox"><div><span>KMITORA understanding</span><strong>{pct}%</strong></div><div className="ko-progress"><i style={{width:`${pct}%`}}/></div></div>
   <div className="ko-actions"><button className="ko-secondary" onClick={onView}>View {label==="SOURCE"?"Source":"Target"} Data</button><button className="ko-ghost" onClick={onUnderstand}>System Understanding</button></div></>}
 </section>;
}

export default function KMITORAEnterpriseOS({source,target,understanding,readiness,adapter={}}:Props){
 const [draft,setDraft]=useState<RequirementDraft>({prompt:"",attachments:[]}); const [ask,setAsk]=useState("");
 const r=useMemo<ReadinessSummary>(()=>({sourceReady:source.status==="connected",targetReady:target.status==="connected",requirementReady:Boolean(understanding),planReady:false,dryRunReady:false,migrationAuthorized:false,...readiness}),[source.status,target.status,understanding,readiness]);
 const both=r.sourceReady&&r.targetReady;
 const steps=[["Connect",r.sourceReady&&r.targetReady],["Understand",both],["Requirement",r.requirementReady],["Plan",r.planReady],["Migrate",r.migrationAuthorized],["Verify",false]] as const;
 const add=(type:string,name:string)=>setDraft(d=>({...d,attachments:[...d.attachments,{id:`${type}-${Date.now()}`,name,type}]}));
 return <main className="ko-page">
   <header className="ko-top"><div><b>KMITORA</b><span>Autonomous Enterprise Transformation & Operations OS</span></div><div><button className="ko-ghost" onClick={adapter.openOperations}>Operate</button><button className="ko-ghost" onClick={adapter.openEngineeringView}>Advanced Engineering</button></div></header>
   <section className="ko-hero"><span className="ko-eye">SIMPLE MODE</span><h1>Connect. Understand. Transform. Operate.</h1><p>More intelligence behind the screen. Fewer controls on the screen.</p></section>
   <section className="ko-card ko-stepper">{steps.map(([n,done],i)=><React.Fragment key={n}><div className={done?"done":""}><span>{done?"✓":i+1}</span><b>{n}</b></div>{i<steps.length-1&&<i className={done?"done":""}/>}</React.Fragment>)}</section>
   <div className="ko-grid"><SystemCard label="SOURCE" system={source} onConnect={adapter.connectSource} onView={adapter.openSourceData} onUnderstand={adapter.openSourceUnderstanding}/><div className={`ko-bridge ${both?"ready":""}`}><strong>↔</strong><b>{both?"KMITORA READY":"CONNECT BOTH SYSTEMS"}</b><small>{both?"Source ↔ Target intelligence established":"Automatic understanding starts after connection"}</small></div><SystemCard label="TARGET" system={target} onConnect={adapter.connectTarget} onView={adapter.openTargetData} onUnderstand={adapter.openTargetUnderstanding}/></div>
   {both&&<section className="ko-card ko-requirement"><div className="ko-head"><div><span className="ko-eye">BUSINESS INTENT</span><h2>What do you want KMITORA to do?</h2></div><span className="ko-pill">Prompt + Documents + Diagrams</span></div><textarea value={draft.prompt} onChange={e=>setDraft({...draft,prompt:e.target.value})} placeholder="Example: Migrate active customers and open orders, consolidate duplicates, preserve historical references and apply target business rules."/><div className="ko-chips"><button onClick={()=>add("document","Business document")}>+ Document</button><button onClick={()=>add("mapping","Mapping sheet")}>+ Mapping</button><button onClick={()=>add("diagram","Architecture diagram")}>+ Diagram</button><button onClick={()=>add("rules","Business rules")}>+ Rules</button><button onClick={()=>add("sample","Sample data")}>+ Sample</button><button onClick={()=>add("api","API specification")}>+ API</button></div>{draft.attachments.length>0&&<div className="ko-files">{draft.attachments.map(a=><span key={a.id}>{a.name}</span>)}</div>}<div className="ko-actions end"><small>KMITORA interprets intent, discovers scope and generates the migration plan.</small><button className="ko-primary" disabled={!draft.prompt.trim()&&!draft.attachments.length} onClick={()=>adapter.analyseRequirement?.(draft)}>Analyse Requirement</button></div></section>}
   {understanding&&<section className="ko-card ko-understood"><div className="ko-head"><div><span className="ko-eye">KMITORA UNDERSTANDING</span><h2>{understanding.domain||"Business requirement understood"}</h2><p>{understanding.scopeSummary}</p></div>{understanding.confidence!==undefined&&<div className="ko-confidence"><strong>{understanding.confidence}%</strong><span>Confidence</span></div>}</div><div className="ko-summary">{[["Source objects",understanding.sourceObjects],["Target objects",understanding.targetObjects],["Dependencies",understanding.dependencies],["Business rules",understanding.businessRules],["Transformations",understanding.transformations],["Reference mappings",understanding.referenceMappings],["Conflicts",understanding.conflicts],["Missing info",understanding.missingInformation]].map(([k,v])=>v===undefined?null:<div key={String(k)}><strong>{v}</strong><span>{k}</span></div>)}</div>{understanding.bullets?.map(x=><p className="ko-check" key={x}>✓ {x}</p>)}<div className="ko-actions"><button className="ko-secondary" onClick={adapter.openRequirementReview}>Review Understanding</button><button className="ko-primary" onClick={adapter.openPlan}>Continue to Discover</button></div></section>}
   <section className="ko-card ko-assistant"><div><span className="ko-eye">ASK KMITORA</span><h2>Control the platform in natural language</h2></div><div><input value={ask} onChange={e=>setAsk(e.target.value)} placeholder="Ask about dependencies, mappings, risks, issues or readiness..."/><button className="ko-primary" disabled={!ask.trim()} onClick={()=>{adapter.askKmitora?.(ask.trim());setAsk("")}}>Ask</button></div></section>
   <section className="ko-card ko-safety"><div><b>Autonomous analysis</b><span>Enabled</span></div><div><b>Production migration</b><span>Governed</span></div><div><b>Cutover</b><span>Explicit authorization required</span></div></section>
 </main>;
}

