export type DomainKind = "INDUSTRY" | "HORIZONTAL";

export type DomainDefinition = {
  id: number;
  name: string;
  kind: DomainKind;
  majorDataAreas: string;
  typicalSystems: string;
  migrationUse: string;
};

export const universalDomainRegistry: DomainDefinition[] = [
  { id: 1, name: "Banking & Financial Services", kind: "INDUSTRY", majorDataAreas: "Customers, accounts, deposits, loans, payments, transactions, cards, KYC", typicalSystems: "Core Banking, Temenos, Finacle, Oracle FLEXCUBE, SAP", migrationUse: "Core banking migration, DW, regulatory reporting" },
  { id: 2, name: "Insurance", kind: "INDUSTRY", majorDataAreas: "Policies, claims, premiums, customers, underwriting, agents", typicalSystems: "Guidewire, Duck Creek, SAP, Oracle", migrationUse: "Policy/claims migration, actuarial DW" },
  { id: 3, name: "Telecommunications", kind: "INDUSTRY", majorDataAreas: "Subscribers, SIM, network, usage, billing, CDR, plans", typicalSystems: "Amdocs, Ericsson, Nokia, Netcracker", migrationUse: "BSS/OSS migration, CDR processing" },
  { id: 4, name: "Healthcare", kind: "INDUSTRY", majorDataAreas: "Patients, encounters, diagnoses, medications, providers", typicalSystems: "Epic, Cerner, Oracle Health, SAP", migrationUse: "EHR migration, clinical DW" },
  { id: 5, name: "Pharmaceuticals", kind: "INDUSTRY", majorDataAreas: "Drugs, clinical trials, manufacturing, batches, quality", typicalSystems: "SAP, Veeva, Lab systems", migrationUse: "Pharma ERP/clinical migration" },
  { id: 6, name: "Life Sciences", kind: "INDUSTRY", majorDataAreas: "Research, genomics, trials, laboratory data", typicalSystems: "Veeva, LIMS, ELN", migrationUse: "Research-data integration" },
  { id: 7, name: "Government / Public Sector", kind: "INDUSTRY", majorDataAreas: "Citizens, departments, benefits, taxation, permits", typicalSystems: "Government ERP, custom systems", migrationUse: "e-Governance modernization" },
  { id: 8, name: "Education", kind: "INDUSTRY", majorDataAreas: "Students, teachers, courses, assessments, attendance", typicalSystems: "SIS, LMS, ERP", migrationUse: "SIS/LMS/DW migration" },
  { id: 9, name: "Retail", kind: "INDUSTRY", majorDataAreas: "Customers, products, stores, sales, inventory, promotions", typicalSystems: "SAP, Oracle, Salesforce", migrationUse: "Retail modernization" },
  { id: 10, name: "E-Commerce", kind: "INDUSTRY", majorDataAreas: "Products, carts, orders, payments, customers", typicalSystems: "Shopify, Magento, Salesforce Commerce", migrationUse: "Platform migration" },
  { id: 11, name: "Manufacturing", kind: "INDUSTRY", majorDataAreas: "Products, BOM, production, inventory, quality", typicalSystems: "SAP, Oracle, MES", migrationUse: "ERP/MES migration" },
  { id: 12, name: "Automotive", kind: "INDUSTRY", majorDataAreas: "Vehicles, parts, dealers, production, warranty", typicalSystems: "SAP, Oracle, PLM, MES", migrationUse: "Automotive ERP/data migration" },
  { id: 13, name: "Aerospace & Defense", kind: "INDUSTRY", majorDataAreas: "Aircraft, parts, maintenance, engineering, supply chain", typicalSystems: "SAP, PLM, MES", migrationUse: "Engineering/ERP migration" },
  { id: 14, name: "Energy & Utilities", kind: "INDUSTRY", majorDataAreas: "Electricity, gas, meters, customers, consumption", typicalSystems: "SAP IS-U, Oracle Utilities", migrationUse: "Utility CIS/MDM migration" },
  { id: 15, name: "Oil & Gas", kind: "INDUSTRY", majorDataAreas: "Wells, drilling, production, pipelines, assets", typicalSystems: "SAP, OSIsoft, Oracle", migrationUse: "Upstream/downstream migration" },
  { id: 16, name: "Mining & Metals", kind: "INDUSTRY", majorDataAreas: "Mines, minerals, equipment, production", typicalSystems: "SAP, Maximo", migrationUse: "Asset/ERP migration" },
  { id: 17, name: "Chemicals", kind: "INDUSTRY", majorDataAreas: "Materials, formulas, batches, plants, compliance", typicalSystems: "SAP", migrationUse: "Process manufacturing migration" },
  { id: 18, name: "Agriculture", kind: "INDUSTRY", majorDataAreas: "Farms, crops, livestock, weather, yield", typicalSystems: "Agri platforms, IoT", migrationUse: "Agri-data integration" },
  { id: 19, name: "Food & Beverage", kind: "INDUSTRY", majorDataAreas: "Recipes, batches, suppliers, inventory, quality", typicalSystems: "SAP, Oracle", migrationUse: "Food manufacturing migration" },
  { id: 20, name: "Transportation", kind: "INDUSTRY", majorDataAreas: "Vehicles, routes, passengers, cargo", typicalSystems: "TMS, ERP", migrationUse: "Transport-system migration" },
  { id: 21, name: "Logistics & Supply Chain", kind: "INDUSTRY", majorDataAreas: "Shipments, warehouses, inventory, suppliers", typicalSystems: "SAP, Oracle, Manhattan", migrationUse: "SCM migration" },
  { id: 22, name: "Airlines", kind: "INDUSTRY", majorDataAreas: "Passengers, flights, tickets, loyalty, baggage", typicalSystems: "Amadeus, Sabre", migrationUse: "Airline platform migration" },
  { id: 23, name: "Railways", kind: "INDUSTRY", majorDataAreas: "Trains, schedules, passengers, assets", typicalSystems: "Rail ERP/custom", migrationUse: "Railway modernization" },
  { id: 24, name: "Shipping / Maritime", kind: "INDUSTRY", majorDataAreas: "Vessels, containers, cargo, ports", typicalSystems: "Maritime ERP/TMS", migrationUse: "Port/logistics migration" },
  { id: 25, name: "Travel & Tourism", kind: "INDUSTRY", majorDataAreas: "Reservations, hotels, flights, customers", typicalSystems: "Amadeus, Sabre, PMS", migrationUse: "Travel-platform migration" },
  { id: 26, name: "Hospitality", kind: "INDUSTRY", majorDataAreas: "Guests, rooms, reservations, billing", typicalSystems: "OPERA, PMS", migrationUse: "PMS migration" },
  { id: 27, name: "Real Estate", kind: "INDUSTRY", majorDataAreas: "Properties, tenants, leases, sales", typicalSystems: "SAP, Salesforce, Yardi", migrationUse: "Property-data migration" },
  { id: 28, name: "Construction", kind: "INDUSTRY", majorDataAreas: "Projects, contracts, materials, labor", typicalSystems: "SAP, Oracle, Procore", migrationUse: "Project/ERP migration" },
  { id: 29, name: "Engineering", kind: "INDUSTRY", majorDataAreas: "Projects, drawings, assets, specifications", typicalSystems: "PLM, CAD, PDM", migrationUse: "Engineering-data migration" },
  { id: 30, name: "Architecture", kind: "INDUSTRY", majorDataAreas: "Designs, buildings, drawings, projects", typicalSystems: "BIM, CAD", migrationUse: "BIM/data integration" },
  { id: 31, name: "Media & Entertainment", kind: "INDUSTRY", majorDataAreas: "Content, users, rights, subscriptions", typicalSystems: "CMS, DAM, OTT", migrationUse: "Content-platform migration" },
  { id: 32, name: "Film / Cinema", kind: "INDUSTRY", majorDataAreas: "Movies, theaters, bookings, rights", typicalSystems: "ERP, ticketing", migrationUse: "Cinema-data integration" },
  { id: 33, name: "Broadcasting", kind: "INDUSTRY", majorDataAreas: "Programs, schedules, advertisements, subscribers", typicalSystems: "Broadcast systems", migrationUse: "Media migration" },
  { id: 34, name: "Gaming", kind: "INDUSTRY", majorDataAreas: "Players, games, transactions, achievements", typicalSystems: "Game platforms", migrationUse: "Gaming-data migration" },
  { id: 35, name: "Advertising & Marketing", kind: "INDUSTRY", majorDataAreas: "Campaigns, leads, audiences, engagement", typicalSystems: "Salesforce, Adobe, HubSpot", migrationUse: "MarTech migration" },
  { id: 36, name: "Professional Services", kind: "INDUSTRY", majorDataAreas: "Clients, projects, consultants, billing", typicalSystems: "ERP, PSA, CRM", migrationUse: "PSA/ERP migration" },
  { id: 37, name: "IT Services", kind: "INDUSTRY", majorDataAreas: "Customers, projects, tickets, assets, resources", typicalSystems: "ServiceNow, SAP, Salesforce", migrationUse: "ITSM/ERP migration" },
  { id: 38, name: "Software / Technology", kind: "INDUSTRY", majorDataAreas: "Users, subscriptions, licenses, telemetry", typicalSystems: "CRM, SaaS platforms", migrationUse: "SaaS/customer migration" },
  { id: 39, name: "Human Resources", kind: "INDUSTRY", majorDataAreas: "Employees, payroll, benefits, recruitment", typicalSystems: "Workday, SAP SuccessFactors", migrationUse: "HRMS migration" },
  { id: 40, name: "Payroll", kind: "INDUSTRY", majorDataAreas: "Salary, tax, deductions, attendance", typicalSystems: "SAP, ADP, Workday", migrationUse: "Payroll migration" },
  { id: 41, name: "Legal", kind: "INDUSTRY", majorDataAreas: "Matters, cases, contracts, documents", typicalSystems: "Legal platforms", migrationUse: "Legal-system migration" },
  { id: 42, name: "Accounting", kind: "INDUSTRY", majorDataAreas: "GL, AP, AR, assets, journals", typicalSystems: "SAP, Oracle, Dynamics", migrationUse: "Financial migration" },
  { id: 43, name: "Taxation", kind: "INDUSTRY", majorDataAreas: "Taxpayers, returns, invoices, assessments", typicalSystems: "Government/custom", migrationUse: "Tax-system modernization" },
  { id: 44, name: "Audit & Compliance", kind: "INDUSTRY", majorDataAreas: "Controls, findings, evidence, risks", typicalSystems: "GRC platforms", migrationUse: "GRC migration" },
  { id: 45, name: "Investment Management", kind: "INDUSTRY", majorDataAreas: "Portfolios, securities, trades, NAV", typicalSystems: "Bloomberg, Aladdin, SimCorp", migrationUse: "Investment-data migration" },
  { id: 46, name: "Capital Markets", kind: "INDUSTRY", majorDataAreas: "Orders, trades, securities, market data", typicalSystems: "Trading platforms", migrationUse: "Trading/DW migration" },
  { id: 47, name: "Stock Exchanges", kind: "INDUSTRY", majorDataAreas: "Orders, trades, instruments, market data", typicalSystems: "Exchange systems", migrationUse: "Market-data migration" },
  { id: 48, name: "Payments", kind: "INDUSTRY", majorDataAreas: "Transactions, merchants, cards, settlement", typicalSystems: "Payment gateways, ISO 20022", migrationUse: "Payment migration" },
  { id: 49, name: "FinTech", kind: "INDUSTRY", majorDataAreas: "Wallets, payments, lending, identity", typicalSystems: "FinTech platforms", migrationUse: "Digital-finance migration" },
  { id: 50, name: "Credit / Lending", kind: "INDUSTRY", majorDataAreas: "Applicants, credit scores, loans, repayments", typicalSystems: "Lending platforms", migrationUse: "Loan migration" },
  { id: 51, name: "Wealth Management", kind: "INDUSTRY", majorDataAreas: "Clients, portfolios, assets, advisors", typicalSystems: "Wealth platforms", migrationUse: "Wealth-data migration" },
  { id: 52, name: "Pension / Retirement", kind: "INDUSTRY", majorDataAreas: "Members, contributions, benefits", typicalSystems: "Pension platforms", migrationUse: "Pension migration" },
  { id: 53, name: "Government Benefits", kind: "INDUSTRY", majorDataAreas: "Welfare, beneficiaries, eligibility", typicalSystems: "Government systems", migrationUse: "Benefits migration" },
  { id: 54, name: "Social Security", kind: "INDUSTRY", majorDataAreas: "Citizens, contributions, benefits", typicalSystems: "Government systems", migrationUse: "Social-security migration" },
  { id: 55, name: "Defense / Military", kind: "INDUSTRY", majorDataAreas: "Personnel, equipment, logistics, missions", typicalSystems: "Defense systems", migrationUse: "Secure-system migration" },
  { id: 56, name: "Space", kind: "INDUSTRY", majorDataAreas: "Satellites, telemetry, missions, ground systems", typicalSystems: "Mission systems", migrationUse: "Scientific/telemetry migration" },
  { id: 57, name: "Science & Research", kind: "INDUSTRY", majorDataAreas: "Experiments, datasets, instruments", typicalSystems: "Research platforms", migrationUse: "Research-data integration" },
  { id: 58, name: "Weather & Climate", kind: "INDUSTRY", majorDataAreas: "Weather, climate, satellite, sensors", typicalSystems: "NOAA-like systems, GIS", migrationUse: "Scientific-data migration" },
  { id: 59, name: "Environmental", kind: "INDUSTRY", majorDataAreas: "Air, water, waste, pollution", typicalSystems: "GIS/IoT", migrationUse: "Environmental-data integration" },
  { id: 60, name: "Smart Cities", kind: "INDUSTRY", majorDataAreas: "Traffic, utilities, citizens, IoT", typicalSystems: "IoT, GIS, city platforms", migrationUse: "Smart-city integration" },
  { id: 61, name: "IoT", kind: "INDUSTRY", majorDataAreas: "Sensors, devices, telemetry, events", typicalSystems: "IoT platforms, Kafka", migrationUse: "Streaming migration" },
  { id: 62, name: "Cybersecurity", kind: "INDUSTRY", majorDataAreas: "Events, incidents, identities, vulnerabilities", typicalSystems: "SIEM, SOAR", migrationUse: "Security-data migration" },
  { id: 63, name: "Identity & Access Management", kind: "INDUSTRY", majorDataAreas: "Users, roles, permissions, credentials", typicalSystems: "IAM, Active Directory", migrationUse: "IAM migration" },
  { id: 64, name: "Supply Chain", kind: "INDUSTRY", majorDataAreas: "Suppliers, orders, inventory, logistics", typicalSystems: "SAP SCM, Oracle SCM", migrationUse: "SCM transformation" },
  { id: 65, name: "Procurement", kind: "INDUSTRY", majorDataAreas: "Vendors, RFQs, POs, invoices", typicalSystems: "SAP Ariba, Oracle", migrationUse: "Procurement migration" },
  { id: 66, name: "Wholesale", kind: "INDUSTRY", majorDataAreas: "Dealers, products, orders, inventory", typicalSystems: "ERP/CRM", migrationUse: "Wholesale migration" },
  { id: 67, name: "Consumer Goods", kind: "INDUSTRY", majorDataAreas: "Products, customers, distribution", typicalSystems: "SAP, Salesforce", migrationUse: "CPG migration" },
  { id: 68, name: "Fashion & Apparel", kind: "INDUSTRY", majorDataAreas: "Styles, sizes, colors, inventory", typicalSystems: "PLM/ERP", migrationUse: "Fashion ERP migration" },
  { id: 69, name: "Luxury Goods", kind: "INDUSTRY", majorDataAreas: "Products, customers, stores, provenance", typicalSystems: "ERP/CRM", migrationUse: "Customer/product migration" },
  { id: 70, name: "Electronics", kind: "INDUSTRY", majorDataAreas: "Products, components, manufacturing, warranty", typicalSystems: "SAP, PLM", migrationUse: "Product-data migration" },
  { id: 71, name: "Semiconductors", kind: "INDUSTRY", majorDataAreas: "Chips, wafers, fabs, process data", typicalSystems: "MES, PLM", migrationUse: "Manufacturing migration" },
  { id: 72, name: "Utilities – Water", kind: "INDUSTRY", majorDataAreas: "Customers, meters, consumption, billing", typicalSystems: "Utility CIS", migrationUse: "Utility migration" },
  { id: 73, name: "Waste Management", kind: "INDUSTRY", majorDataAreas: "Collection, routes, facilities, waste streams", typicalSystems: "GIS/TMS", migrationUse: "Municipal-data migration" },
  { id: 74, name: "Postal / Courier", kind: "INDUSTRY", majorDataAreas: "Parcels, addresses, routes, customers", typicalSystems: "Logistics systems", migrationUse: "Postal migration" },
  { id: 75, name: "Healthcare Insurance", kind: "INDUSTRY", majorDataAreas: "Members, providers, claims, authorizations", typicalSystems: "Payer platforms", migrationUse: "Claims migration" },
  { id: 76, name: "Medical Devices", kind: "INDUSTRY", majorDataAreas: "Devices, batches, quality, regulatory", typicalSystems: "SAP, PLM", migrationUse: "Device-data migration" },
  { id: 77, name: "Biotechnology", kind: "INDUSTRY", majorDataAreas: "Research, samples, experiments", typicalSystems: "LIMS/ELN", migrationUse: "Scientific migration" },
  { id: 78, name: "Clinical Research", kind: "INDUSTRY", majorDataAreas: "Patients, protocols, trials, observations", typicalSystems: "EDC/CTMS", migrationUse: "Clinical migration" },
  { id: 79, name: "Laboratory / Diagnostics", kind: "INDUSTRY", majorDataAreas: "Samples, tests, results", typicalSystems: "LIS/LIMS", migrationUse: "Laboratory migration" },
  { id: 80, name: "Hospital Management", kind: "INDUSTRY", majorDataAreas: "Admissions, beds, billing, clinical records", typicalSystems: "HIS/ERP", migrationUse: "Hospital migration" },
  { id: 81, name: "Pharmacy", kind: "INDUSTRY", majorDataAreas: "Medicines, prescriptions, inventory", typicalSystems: "Pharmacy systems", migrationUse: "Pharmacy migration" },
  { id: 82, name: "Fitness / Wellness", kind: "INDUSTRY", majorDataAreas: "Members, programs, sessions, payments", typicalSystems: "CRM/ERP", migrationUse: "Membership migration" },
  { id: 83, name: "Sports", kind: "INDUSTRY", majorDataAreas: "Players, teams, events, statistics", typicalSystems: "Sports platforms", migrationUse: "Sports-data migration" },
  { id: 84, name: "Utilities – Gas", kind: "INDUSTRY", majorDataAreas: "Customers, meters, consumption, billing", typicalSystems: "CIS/MDM", migrationUse: "Utility migration" },
  { id: 85, name: "Utilities – Power", kind: "INDUSTRY", majorDataAreas: "Grid, meters, customers, consumption", typicalSystems: "SCADA/MDMS/SAP", migrationUse: "Energy migration" },
  { id: 86, name: "Renewable Energy", kind: "INDUSTRY", majorDataAreas: "Solar, wind, generation, assets", typicalSystems: "SCADA/IoT/ERP", migrationUse: "Energy-data migration" },
  { id: 87, name: "Banking Risk", kind: "INDUSTRY", majorDataAreas: "Credit, market, operational risk", typicalSystems: "Risk platforms", migrationUse: "Risk DW migration" },
  { id: 88, name: "Fraud & AML", kind: "INDUSTRY", majorDataAreas: "Transactions, alerts, cases, customers", typicalSystems: "AML platforms", migrationUse: "Compliance migration" },
  { id: 89, name: "CRM / Customer Management", kind: "INDUSTRY", majorDataAreas: "Leads, customers, contacts, interactions", typicalSystems: "Salesforce, Dynamics", migrationUse: "CRM migration" },
  { id: 90, name: "Enterprise Asset Management", kind: "INDUSTRY", majorDataAreas: "Equipment, maintenance, work orders", typicalSystems: "SAP PM, Maximo", migrationUse: "EAM migration" },
  { id: 91, name: "PLM", kind: "INDUSTRY", majorDataAreas: "Products, BOM, revisions, engineering", typicalSystems: "Teamcenter, Windchill", migrationUse: "PLM migration" },
  { id: 92, name: "MES", kind: "INDUSTRY", majorDataAreas: "Production, machines, quality, operations", typicalSystems: "Siemens, SAP MES", migrationUse: "Manufacturing migration" },
  { id: 93, name: "GIS / Geospatial", kind: "INDUSTRY", majorDataAreas: "Coordinates, maps, boundaries, assets", typicalSystems: "Esri, PostGIS", migrationUse: "GIS migration" },
  { id: 94, name: "Document Management", kind: "INDUSTRY", majorDataAreas: "Documents, versions, metadata", typicalSystems: "SharePoint, OpenText", migrationUse: "ECM migration" },
  { id: 95, name: "Content Management", kind: "INDUSTRY", majorDataAreas: "Articles, media, metadata", typicalSystems: "CMS", migrationUse: "CMS migration" },
  { id: 96, name: "Knowledge Management", kind: "INDUSTRY", majorDataAreas: "Documents, knowledge articles, relationships", typicalSystems: "KM platforms", migrationUse: "Knowledge migration" },
  { id: 97, name: "Records Management", kind: "INDUSTRY", majorDataAreas: "Records, retention, classification", typicalSystems: "ECM", migrationUse: "Records migration" },
  { id: 98, name: "Data Governance", kind: "INDUSTRY", majorDataAreas: "Policies, owners, definitions, quality", typicalSystems: "Collibra, Informatica", migrationUse: "Governance migration" },
  { id: 99, name: "Master Data Management", kind: "INDUSTRY", majorDataAreas: "Customer, product, supplier, location", typicalSystems: "MDM platforms", migrationUse: "MDM migration" },
  { id: 100, name: "Data Warehousing / BI", kind: "INDUSTRY", majorDataAreas: "Facts, dimensions, metrics, reports", typicalSystems: "BW, Snowflake, Teradata", migrationUse: "DW modernization" },
  { id: 101, name: "ERP", kind: "HORIZONTAL", majorDataAreas: "Finance, procurement, inventory, projects", typicalSystems: "", migrationUse: "" },
  { id: 102, name: "CRM", kind: "HORIZONTAL", majorDataAreas: "Customers, leads, opportunities", typicalSystems: "", migrationUse: "" },
  { id: 103, name: "SCM", kind: "HORIZONTAL", majorDataAreas: "Supply chain, logistics, suppliers", typicalSystems: "", migrationUse: "" },
  { id: 104, name: "HCM", kind: "HORIZONTAL", majorDataAreas: "Employees, organization, payroll", typicalSystems: "", migrationUse: "" },
  { id: 105, name: "EAM", kind: "HORIZONTAL", majorDataAreas: "Assets, maintenance", typicalSystems: "", migrationUse: "" },
  { id: 106, name: "PLM", kind: "HORIZONTAL", majorDataAreas: "Products, engineering", typicalSystems: "", migrationUse: "" },
  { id: 107, name: "MES", kind: "HORIZONTAL", majorDataAreas: "Manufacturing execution", typicalSystems: "", migrationUse: "" },
  { id: 108, name: "WMS", kind: "HORIZONTAL", majorDataAreas: "Warehouses, inventory", typicalSystems: "", migrationUse: "" },
  { id: 109, name: "TMS", kind: "HORIZONTAL", majorDataAreas: "Transportation", typicalSystems: "", migrationUse: "" },
  { id: 110, name: "LMS", kind: "HORIZONTAL", majorDataAreas: "Learning, courses, assessments", typicalSystems: "", migrationUse: "" },
  { id: 111, name: "SIS", kind: "HORIZONTAL", majorDataAreas: "Students, academics", typicalSystems: "", migrationUse: "" },
  { id: 112, name: "CMS", kind: "HORIZONTAL", majorDataAreas: "Content", typicalSystems: "", migrationUse: "" },
  { id: 113, name: "ECM", kind: "HORIZONTAL", majorDataAreas: "Enterprise documents", typicalSystems: "", migrationUse: "" },
  { id: 114, name: "BPM", kind: "HORIZONTAL", majorDataAreas: "Business processes", typicalSystems: "", migrationUse: "" },
  { id: 115, name: "ITSM", kind: "HORIZONTAL", majorDataAreas: "Incidents, problems, changes", typicalSystems: "", migrationUse: "" },
  { id: 116, name: "GRC", kind: "HORIZONTAL", majorDataAreas: "Governance, risk, compliance", typicalSystems: "", migrationUse: "" },
  { id: 117, name: "MDM", kind: "HORIZONTAL", majorDataAreas: "Master data", typicalSystems: "", migrationUse: "" },
  { id: 118, name: "CDP", kind: "HORIZONTAL", majorDataAreas: "Customer data", typicalSystems: "", migrationUse: "" },
  { id: 119, name: "Data Lake", kind: "HORIZONTAL", majorDataAreas: "Raw/large-scale data", typicalSystems: "", migrationUse: "" },
  { id: 120, name: "Data Warehouse", kind: "HORIZONTAL", majorDataAreas: "Analytical data", typicalSystems: "", migrationUse: "" },
  { id: 121, name: "Data Mart", kind: "HORIZONTAL", majorDataAreas: "Departmental analytics", typicalSystems: "", migrationUse: "" },
  { id: 122, name: "Data Mesh", kind: "HORIZONTAL", majorDataAreas: "Domain-oriented data products", typicalSystems: "", migrationUse: "" },
  { id: 123, name: "Data Fabric", kind: "HORIZONTAL", majorDataAreas: "Integrated data access", typicalSystems: "", migrationUse: "" },
  { id: 124, name: "Lakehouse", kind: "HORIZONTAL", majorDataAreas: "Unified analytical platform", typicalSystems: "", migrationUse: "" },
  { id: 125, name: "Operational Data Store", kind: "HORIZONTAL", majorDataAreas: "Near-real-time operational data", typicalSystems: "", migrationUse: "" },
  { id: 126, name: "Metadata Management", kind: "HORIZONTAL", majorDataAreas: "Technical/business metadata", typicalSystems: "", migrationUse: "" },
  { id: 127, name: "Data Catalog", kind: "HORIZONTAL", majorDataAreas: "Discoverability", typicalSystems: "", migrationUse: "" },
  { id: 128, name: "Data Quality", kind: "HORIZONTAL", majorDataAreas: "Quality rules and measurements", typicalSystems: "", migrationUse: "" },
  { id: 129, name: "Data Lineage", kind: "HORIZONTAL", majorDataAreas: "Source-to-target traceability", typicalSystems: "", migrationUse: "" },
  { id: 130, name: "Data Security", kind: "HORIZONTAL", majorDataAreas: "Protection and access", typicalSystems: "", migrationUse: "" },
  { id: 131, name: "API Management", kind: "HORIZONTAL", majorDataAreas: "API lifecycle", typicalSystems: "", migrationUse: "" },
  { id: 132, name: "Event Management", kind: "HORIZONTAL", majorDataAreas: "Event streams", typicalSystems: "", migrationUse: "" },
  { id: 133, name: "Master Reference Data", kind: "HORIZONTAL", majorDataAreas: "Common codes", typicalSystems: "", migrationUse: "" },
  { id: 134, name: "Enterprise Integration", kind: "HORIZONTAL", majorDataAreas: "Cross-system integration", typicalSystems: "", migrationUse: "" },
  { id: 135, name: "Business Intelligence", kind: "HORIZONTAL", majorDataAreas: "Reporting/analytics", typicalSystems: "", migrationUse: "" },
  { id: 136, name: "Advanced Analytics", kind: "HORIZONTAL", majorDataAreas: "Statistical/ML analytics", typicalSystems: "", migrationUse: "" },
  { id: 137, name: "AI/ML Data Platform", kind: "HORIZONTAL", majorDataAreas: "Training/inference data", typicalSystems: "", migrationUse: "" },
  { id: 138, name: "Real-Time Analytics", kind: "HORIZONTAL", majorDataAreas: "Streaming analytics", typicalSystems: "", migrationUse: "" },
  { id: 139, name: "Regulatory Reporting", kind: "HORIZONTAL", majorDataAreas: "Compliance reporting", typicalSystems: "", migrationUse: "" },
  { id: 140, name: "Enterprise Search", kind: "HORIZONTAL", majorDataAreas: "Unified information retrieval", typicalSystems: "", migrationUse: "" },
];

export const businessDomainHierarchy = {
  business: ["Customer","Product","Supplier","Employee","Finance","Asset","Contract","Order","Inventory","Payment","Project","Location"],
  application: ["ERP","CRM","HCM","SCM","EAM","PLM","MES","WMS","TMS","LMS","SIS","ITSM"],
  data: ["Transactional","Master","Reference","Historical","Analytical","Operational","Streaming","Spatial","Document","Multimedia"],
  structure: ["Relational","Hierarchical","XML","JSON","CSV","Avro","Parquet","Binary","Text","Unstructured"],
  transformation: ["Mapping","Cleansing","Validation","Join","Lookup","Aggregation","Deduplication","CDC","SCD","Enrichment","Conversion","Restructuring","Reconciliation","Business Rules"],
} as const;

export const canonicalMigrationRepresentation = [
  "Entity","Relationship","Business Rule","Transformation","Target Entity","Validation","Reconciliation",
] as const;

