export type NeuralStage =
  | "UNDERSTAND" | "DISCOVER" | "DETECT" | "DIAGNOSE" | "PREDICT"
  | "RECOMMEND" | "SIMULATE" | "EXECUTE" | "TEST" | "VALIDATE"
  | "RECONCILE" | "EVIDENCE" | "LEARN";

export type NeuralCapabilityStatus = "REUSE_EXISTING" | "NATIVE_MODEL" | "MODEL_ADAPTER" | "RESEARCH_ONLY";

export type NeuralCapability = {
  id: string;
  name: string;
  category: string;
  description: string;
  stages: NeuralStage[];
  status: NeuralCapabilityStatus;
  reuseId?: string;
  modelFamilies: string[];
  inputs: string[];
  outputs: string[];
  governance: string;
  evidence: string[];
};

export const REUSED_KMITORA_CAPABILITIES = [
  { id: "knowledge-graph", purpose: "Knowledge graph, graph context, dependency and evidence reuse" },
  { id: "metadata-lineage", purpose: "Verified lineage and inferred-lineage comparison" },
  { id: "data-observability", purpose: "Drift, volume, freshness and distribution monitoring" },
  { id: "mdm-entity-resolution", purpose: "Entity resolution and duplicate intelligence" },
  { id: "privacy", purpose: "PII classification, masking and privacy governance" },
  { id: "event-cdc", purpose: "CDC and event-stream intelligence" },
  { id: "database-intelligence", purpose: "Database reverse engineering and metadata discovery" },
  { id: "optimization", purpose: "Scheduling, resource optimization and constraint solving" },
  { id: "causal-probabilistic", purpose: "Root-cause, uncertainty and causal ranking" },
  { id: "aiops-sre", purpose: "Logs, metrics, traces, incidents and operational intelligence" },
  { id: "decision-intelligence", purpose: "Evidence-ranked alternatives, risk and outcome analysis" },
  { id: "digital-twin-runtime", purpose: "Digital twin state, simulation and target preview" },
  { id: "dynamic-agent-runtime", purpose: "A000 specialist routing and governed agent execution" },
] as const;

export const NEURAL_CAPABILITIES: NeuralCapability[] = [
  { id:"neural-db", name:"Neural Database Intelligence", category:"Database", description:"Learned assistance for schema structure, workload, indexes, partitioning, query plans, cardinality, capacity and failure risk.", stages:["DISCOVER","DETECT","PREDICT","RECOMMEND","SIMULATE"], status:"REUSE_EXISTING", reuseId:"database-intelligence", modelFamilies:["Transformer","MLP","Time Series","Gradient Models"], inputs:["catalog metadata","query plans","workload metrics","table statistics"], outputs:["risk findings","optimization candidates","capacity forecast"], governance:"Read-only analysis by default; no DDL or production tuning without approval.", evidence:["metadata snapshot","plan evidence","metric window"] },
  { id:"schema-semantic", name:"Semantic Schema Intelligence", category:"Schema", description:"Understands table and column meaning using names, datatypes, sample values, domain context and lineage.", stages:["UNDERSTAND","DISCOVER","RECOMMEND","VALIDATE"], status:"NATIVE_MODEL", modelFamilies:["Embedding","Transformer","Contrastive"], inputs:["schemas","column names","sample values","domain context"], outputs:["semantic labels","schema similarity","datatype intent"], governance:"Recommendations require deterministic compatibility checks before promotion.", evidence:["feature signals","candidate scores","rule checks"] },
  { id:"mapping-neural", name:"Neural Mapping Engine", category:"Migration", description:"Ranks source-to-target mapping candidates using semantic, structural, statistical and historical evidence.", stages:["DISCOVER","RECOMMEND","SIMULATE","VALIDATE"], status:"NATIVE_MODEL", modelFamilies:["Siamese Network","Embedding","Learning-to-Rank"], inputs:["source schema","target schema","samples","historical mappings"], outputs:["mapping candidates","confidence decomposition"], governance:"AI proposes; deterministic validators and approval policies govern acceptance.", evidence:["candidate matrix","compatibility checks","lineage links"] },
  { id:"entity-resolution-neural", name:"Entity Resolution Intelligence", category:"Data Quality", description:"Resolves likely same-entity records across systems using identifiers, names, addresses, temporal history and behavioral signals.", stages:["DISCOVER","DETECT","DIAGNOSE","RECOMMEND","VALIDATE"], status:"REUSE_EXISTING", reuseId:"mdm-entity-resolution", modelFamilies:["Siamese Network","Graph Embedding","Probabilistic Matching"], inputs:["identity fields","addresses","phones","emails","temporal history"], outputs:["match candidates","merge risk","evidence features"], governance:"High-risk merges require human or policy approval.", evidence:["feature match evidence","identity graph","rule results"] },
  { id:"neural-dq", name:"Neural Data Quality", category:"Data Quality", description:"Finds multivariate anomalies and subtle inconsistencies beyond static rules.", stages:["DETECT","DIAGNOSE","PREDICT","VALIDATE"], status:"NATIVE_MODEL", modelFamilies:["Autoencoder","Isolation Models","Transformer","Tabular NN"], inputs:["records","distributions","relationships","business rules"], outputs:["anomaly score","cluster","affected fields"], governance:"Never replaces hard business rules; anomaly score is advisory until validated.", evidence:["input features","reconstruction error","rule comparison"] },
  { id:"query-intel", name:"Query Intelligence", category:"Database", description:"Analyzes SQL, query plans, access paths, joins, indexes and runtime behavior.", stages:["DISCOVER","DETECT","DIAGNOSE","RECOMMEND","SIMULATE"], status:"MODEL_ADAPTER", modelFamilies:["Code Transformer","Learned Cost Model","Regression"], inputs:["SQL","query plans","statistics","runtime metrics"], outputs:["cost forecast","index candidates","join recommendations"], governance:"No query-plan or index change is automatically applied to production.", evidence:["query text hash","plan snapshot","runtime baseline"] },
  { id:"cardinality", name:"Learned Cardinality Estimation", category:"Database", description:"Estimates result-set sizes for complex correlated predicates and joins.", stages:["PREDICT","RECOMMEND","SIMULATE"], status:"RESEARCH_ONLY", modelFamilies:["Deep Sets","Transformer","Density Estimation"], inputs:["column statistics","predicate structure","sample distributions"], outputs:["estimated rows","uncertainty"], governance:"Research/simulation until benchmarked against native optimizer statistics.", evidence:["benchmark set","error metrics"] },
  { id:"learned-index", name:"Learned Index Research", category:"Database", description:"Evaluates model-based record location prediction as a research capability.", stages:["PREDICT","SIMULATE"], status:"RESEARCH_ONLY", modelFamilies:["Regression","Piecewise Models"], inputs:["sorted keys","access patterns"], outputs:["lookup estimate","benchmark"], governance:"Never replaces production indexing without explicit engineering validation.", evidence:["benchmark results","latency comparison"] },
  { id:"workload-predict", name:"Workload and Capacity Prediction", category:"Operations", description:"Forecasts CPU, memory, storage, connections, throughput, queue depth and job duration.", stages:["PREDICT","RECOMMEND","SIMULATE"], status:"NATIVE_MODEL", modelFamilies:["LSTM","GRU","TCN","Time-Series Transformer"], inputs:["metrics","job history","data volumes","calendar"], outputs:["forecast","SLA risk","capacity risk"], governance:"Forecasts drive recommendation and simulation, not direct resource changes.", evidence:["metric window","forecast horizon","error bands"] },
  { id:"neural-scheduler", name:"Intelligent Workflow Scheduler", category:"Automation", description:"Uses workload forecasts, dependencies, resource constraints and SLAs to recommend safer job ordering and concurrency.", stages:["PREDICT","RECOMMEND","SIMULATE"], status:"REUSE_EXISTING", reuseId:"optimization", modelFamilies:["Optimization","RL Simulation","Constraint Solver"], inputs:["DAG","SLA","resources","predicted durations"], outputs:["schedule proposal","parallelism","risk score"], governance:"A000 may recommend; schedule mutation remains governed.", evidence:["DAG snapshot","constraint set","simulation result"] },
  { id:"failure-predict", name:"Failure Prediction", category:"Operations", description:"Predicts elevated failure risk from metrics, retries, locks, latency, data volume and historical incidents.", stages:["DETECT","PREDICT","RECOMMEND"], status:"NATIVE_MODEL", modelFamilies:["Classifier","Time Series","Survival Model"], inputs:["metrics","logs","job history","error history"], outputs:["risk level","drivers","time horizon"], governance:"Prediction cannot block execution by itself; policy gates determine action.", evidence:["features","model version","calibration"] },
  { id:"neural-rca", name:"Neural Root Cause Analysis", category:"Diagnosis", description:"Correlates incidents, dependencies, logs, metrics and change history to rank root-cause candidates.", stages:["DIAGNOSE","RECOMMEND","EVIDENCE"], status:"REUSE_EXISTING", reuseId:"causal-probabilistic", modelFamilies:["Graph Neural Network","Causal Model","Embedding"], inputs:["dependency graph","logs","metrics","changes"], outputs:["ranked causes","blast radius","confidence"], governance:"Ranked causes remain hypotheses until evidence-backed checks pass.", evidence:["causal path","supporting events","counter-evidence"] },
  { id:"graph-intel", name:"Graph Neural Intelligence", category:"Graph", description:"Uses enterprise graph structure for dependency prediction, impact analysis, hidden relationship discovery and migration ordering.", stages:["DISCOVER","DIAGNOSE","PREDICT","RECOMMEND"], status:"REUSE_EXISTING", reuseId:"knowledge-graph", modelFamilies:["GCN","GAT","GraphSAGE","Graph Embeddings"], inputs:["knowledge graph","lineage graph","workflow DAG"], outputs:["relationship candidates","impact paths","graph risk"], governance:"Inferred edges are labeled as inferred until verified.", evidence:["graph path","edge score","provenance"] },
  { id:"neural-lineage", name:"Neural Lineage Inference", category:"Lineage", description:"Infers probable lineage when explicit lineage is missing by combining names, values, SQL, ETL logic and timestamps.", stages:["DISCOVER","DIAGNOSE","EVIDENCE"], status:"REUSE_EXISTING", reuseId:"metadata-lineage", modelFamilies:["Embedding","Graph Model","Transformer"], inputs:["SQL","ETL metadata","schemas","samples"], outputs:["probable lineage","confidence","unresolved gaps"], governance:"Always distinguishes inferred lineage from verified lineage.", evidence:["source signals","candidate path","verification status"] },
  { id:"log-intel", name:"Neural Log Intelligence", category:"Operations", description:"Clusters large log volumes into error families, incident patterns and recurring operational signatures.", stages:["DETECT","DIAGNOSE","PREDICT"], status:"REUSE_EXISTING", reuseId:"aiops-sre", modelFamilies:["Sentence Embedding","Transformer","Clustering"], inputs:["database logs","ETL logs","application logs","OS logs"], outputs:["clusters","signatures","incident candidates"], governance:"Log clustering is diagnostic; destructive remediation is never automatic.", evidence:["log hashes","cluster exemplars","time windows"] },
  { id:"timeseries", name:"Time-Series Neural Intelligence", category:"Prediction", description:"Forecasts workload, latency, throughput, storage, queue depth and migration duration.", stages:["PREDICT","RECOMMEND","SIMULATE"], status:"NATIVE_MODEL", modelFamilies:["LSTM","GRU","TCN","Transformer"], inputs:["time-series metrics","batch durations","record counts"], outputs:["forecast","trend","anomaly","prediction interval"], governance:"Prediction intervals and backtest errors must be shown.", evidence:["training window","validation window","forecast error"] },
  { id:"code-intel", name:"Neural Code and Stored Procedure Intelligence", category:"Reverse Engineering", description:"Extracts logic, dependencies, side effects and business rules from SQL, PL/SQL, T-SQL, Java, Python, C#, COBOL and scripts.", stages:["DISCOVER","DIAGNOSE","RECOMMEND"], status:"MODEL_ADAPTER", modelFamilies:["Code Transformer","LLM","Graph Extraction"], inputs:["source code","stored procedures","packages","scripts"], outputs:["rule candidates","dependency edges","side-effect summary"], governance:"Extracted rules are candidates until verified against code evidence and tests.", evidence:["file hash","line references","extracted rule"] },
  { id:"embeddings", name:"Enterprise Embedding Service", category:"Knowledge", description:"Creates governed semantic representations for schemas, rules, mappings, code, logs, workflows and evidence.", stages:["UNDERSTAND","DISCOVER","DIAGNOSE","RECOMMEND","LEARN"], status:"NATIVE_MODEL", modelFamilies:["Text Embedding","Code Embedding","Graph Embedding"], inputs:["metadata","documents","code","logs"], outputs:["vectors","similarity search keys"], governance:"Namespace, tenant and sensitivity controls apply before indexing.", evidence:["embedding model version","source hash","namespace"] },
  { id:"vector-store", name:"Vector Knowledge Store", category:"Knowledge", description:"Indexes embeddings with provenance for semantic retrieval and similarity search.", stages:["UNDERSTAND","DISCOVER","DIAGNOSE","RECOMMEND","LEARN"], status:"MODEL_ADAPTER", modelFamilies:["pgvector","Qdrant","Milvus","OpenSearch","Weaviate"], inputs:["vectors","metadata","ACL"], outputs:["retrieval results","provenance"], governance:"Access control and source provenance are mandatory.", evidence:["retrieval ids","scores","source references"] },
  { id:"rag-db", name:"RAG for Database and Migration Intelligence", category:"Knowledge", description:"Grounds explanations and recommendations in schema, requirements, mappings, rules, code and evidence.", stages:["UNDERSTAND","DISCOVER","DIAGNOSE","RECOMMEND","EVIDENCE"], status:"NATIVE_MODEL", modelFamilies:["RAG","Reranker","LLM"], inputs:["retrieved evidence","user question","migration context"], outputs:["grounded answer","citations","abstention"], governance:"Unsupported claims must abstain; retrieval provenance is retained.", evidence:["retrieval set","answer trace","confidence"] },
  { id:"neural-symbolic", name:"Neural-Symbolic Decision Engine", category:"Governance", description:"Combines neural recommendations with deterministic rules, constraints, graph evidence and policy gates.", stages:["DETECT","DIAGNOSE","PREDICT","RECOMMEND","SIMULATE","VALIDATE"], status:"NATIVE_MODEL", modelFamilies:["Neural Model","Rule Engine","Constraint Solver"], inputs:["model output","rules","policies","evidence"], outputs:["validated recommendation","blocked reason","confidence decomposition"], governance:"No recommendation becomes executable until deterministic validators and policy gates pass.", evidence:["model score","rule results","policy result"] },
  { id:"federated", name:"Federated and Privacy-Preserving Learning", category:"Privacy", description:"Supports local learning with controlled model updates instead of centralizing raw sensitive records.", stages:["LEARN","VALIDATE","EVIDENCE"], status:"RESEARCH_ONLY", modelFamilies:["Federated Learning","Differential Privacy","Secure Aggregation"], inputs:["local gradients or updates","privacy budget"], outputs:["aggregated model","privacy metrics"], governance:"Requires explicit privacy architecture and security review.", evidence:["privacy parameters","participating nodes","aggregation result"] },
  { id:"selfsupervised", name:"Self-Supervised and Contrastive Learning", category:"Learning", description:"Learns reusable representations from unlabeled schemas, SQL, logs, mappings and workflows.", stages:["DISCOVER","LEARN"], status:"RESEARCH_ONLY", modelFamilies:["Masked Modeling","Contrastive Learning"], inputs:["unlabeled enterprise metadata"], outputs:["representations","similarity model"], governance:"Training data lineage and evaluation are required before operational use.", evidence:["dataset version","objective","evaluation"] },
  { id:"model-router", name:"Model Router", category:"Model Ops", description:"Selects deterministic algorithm, embedding model, GNN, time-series model, classifier or LLM based on task and governance.", stages:["UNDERSTAND","DISCOVER","DETECT","DIAGNOSE","PREDICT","RECOMMEND"], status:"NATIVE_MODEL", modelFamilies:["Router","Policy Engine"], inputs:["task type","latency","sensitivity","evaluation history"], outputs:["selected model","fallback","reason"], governance:"Routing policy is versioned and auditable.", evidence:["routing decision","model id","policy version"] },
  { id:"model-registry", name:"Model Registry and Lineage", category:"Model Ops", description:"Tracks model identity, version, purpose, dataset references, evaluation, approval, deployment and drift state.", stages:["VALIDATE","EVIDENCE","LEARN"], status:"NATIVE_MODEL", modelFamilies:["Registry"], inputs:["model metadata","evaluation results"], outputs:["governed model record"], governance:"Unapproved models cannot be promoted to governed execution.", evidence:["model version","evaluation id","approval status"] },
  { id:"model-eval", name:"Model Evaluation and Calibration", category:"Model Ops", description:"Measures accuracy, precision, recall, F1, calibration, false-positive/negative rates, robustness, latency and cost.", stages:["TEST","VALIDATE","EVIDENCE","LEARN"], status:"NATIVE_MODEL", modelFamilies:["Evaluation Harness"], inputs:["gold data","predictions","adversarial cases"], outputs:["metrics","gates","calibration"], governance:"Thresholds are task-specific and versioned.", evidence:["dataset version","metric report","gate result"] },
  { id:"model-drift", name:"Model and Data Drift Monitor", category:"Model Ops", description:"Detects input, concept, performance and embedding drift over time.", stages:["DETECT","PREDICT","VALIDATE","LEARN"], status:"REUSE_EXISTING", reuseId:"data-observability", modelFamilies:["Drift Statistics","Embedding Drift","Performance Monitor"], inputs:["current data","baseline","model metrics"], outputs:["drift score","affected model","revalidation request"], governance:"Drift can block model promotion but not mutate data.", evidence:["baseline","current window","drift test"] },
  { id:"xai", name:"Explainable Neural Intelligence", category:"Governance", description:"Explains recommendations using feature attribution, similarity evidence, graph paths, rule results and model confidence.", stages:["DIAGNOSE","RECOMMEND","VALIDATE","EVIDENCE"], status:"NATIVE_MODEL", modelFamilies:["SHAP-like","Attribution","Counterfactual"], inputs:["prediction","features","rules","graph"], outputs:["reason codes","feature contribution","counterfactual"], governance:"Explanation is mandatory for high-impact recommendations.", evidence:["reason codes","attribution record"] },
  { id:"neural-twin", name:"Neural Digital Twin", category:"Digital Twin", description:"Adds learned behavior, risk and forecast signals to the existing enterprise digital twin without replacing authoritative state.", stages:["PREDICT","RECOMMEND","SIMULATE","EVIDENCE"], status:"REUSE_EXISTING", reuseId:"digital-twin-runtime", modelFamilies:["Graph Model","Time Series","Simulation"], inputs:["twin state","history","dependencies","metrics"], outputs:["forecast state","risk","scenario comparison"], governance:"Authoritative state remains deterministic; learned state is explicitly labeled predicted.", evidence:["twin version","scenario","prediction"] },
  { id:"simulation-intel", name:"Simulation Intelligence", category:"Simulation", description:"Predicts likely outcomes before execution and compares predictions with deterministic dry-run results.", stages:["SIMULATE","VALIDATE","EVIDENCE"], status:"REUSE_EXISTING", reuseId:"decision-intelligence", modelFamilies:["Predictive Model","Simulation","Causal Model"], inputs:["proposed changes","twin","rules","history"], outputs:["expected success","review risk","quarantine risk","uncertainty"], governance:"Prediction never substitutes for deterministic simulation.", evidence:["prediction","dry-run comparison","variance"] },
  { id:"safe-learning", name:"Verified Continuous Learning", category:"Learning", description:"Learns only from verified outcomes, reconciled evidence and approved feedback; rejects unverified runtime stories.", stages:["LEARN","EVIDENCE"], status:"NATIVE_MODEL", modelFamilies:["Online Learning","Retrieval Learning","Evaluation"], inputs:["verified outcomes","evidence","approved feedback"], outputs:["updated retrieval patterns","candidate model update"], governance:"No autonomous retraining or promotion without evaluation and approval.", evidence:["source run","verification status","learning decision"] },
];

export const LIFECYCLE_NEURAL_MAP = [
  ["Understand", "Domain context, embeddings, semantic intent and RAG grounding"],
  ["Discover", "Schema semantics, mapping intelligence, graph relationships, code and lineage discovery"],
  ["Detect", "Neural data-quality, log clustering, failure signals and drift"],
  ["Diagnose", "Causal RCA, graph reasoning, explanations and impact paths"],
  ["Predict", "Time series, workload, capacity, failure and scenario forecasting"],
  ["Recommend", "Ranked mapping, query, scheduling and remediation recommendations"],
  ["Simulate", "Neural forecast compared with deterministic dry-run and digital twin"],
  ["Execute", "Deterministic governed execution only; neural models do not directly mutate production"],
  ["Test", "Model, rule and system tests"],
  ["Validate", "Calibration, rule verification, policy gates and drift checks"],
  ["Reconcile", "Compare predicted, simulated and actual outcomes"],
  ["Evidence", "Model/version/provenance/explanation evidence"],
  ["Learn", "Verified continuous learning only"],
] as const;