import type {
  EnterpriseTwinGraph,
  TwinGraphEdge,
  TwinGraphNode,
  TwinTemporalState,
} from "../models/EnterpriseTwinGraph";

const nodes: TwinGraphNode[] = [
  {
    id: "enterprise",
    label: "Customer Modernization",
    layer: "L0_ENTERPRISE",
    type: "ENTERPRISE_CAPABILITY",
    x: 500,
    y: 52,
    environment: "GLOBAL",
    state: "HEALTHY",
    risk: 8,
    confidence: 99,
    evidenceIds: ["EV-ENT-001"],
    metadata: { owner: "Enterprise Architecture", domain: "Customer" },
  },
  {
    id: "source",
    label: "Legacy Customer DB",
    layer: "L1_SYSTEM",
    type: "DATABASE",
    x: 160,
    y: 180,
    environment: "DEV",
    state: "REVIEW",
    risk: 42,
    confidence: 100,
    evidenceIds: ["EV-SRC-001"],
    metadata: { engine: "Legacy RDBMS", role: "SOURCE" },
  },
  {
    id: "api",
    label: "Customer API",
    layer: "L1_SYSTEM",
    type: "API",
    x: 820,
    y: 180,
    environment: "DEV",
    state: "HEALTHY",
    risk: 15,
    confidence: 98,
    evidenceIds: ["EV-API-001"],
    metadata: { protocol: "REST", version: "v1" },
  },
  {
    id: "schema",
    label: "customer_profile",
    layer: "L2_DATA",
    type: "SCHEMA",
    x: 165,
    y: 320,
    environment: "DEV",
    state: "REVIEW",
    risk: 36,
    confidence: 100,
    evidenceIds: ["EV-DATA-011"],
    metadata: { primaryKey: "customer_id", records: 5 },
  },
  {
    id: "process",
    label: "Customer Migration",
    layer: "L3_PROCESS",
    type: "PROCESS",
    x: 500,
    y: 250,
    environment: "DEV",
    state: "HEALTHY",
    risk: 18,
    confidence: 99,
    evidenceIds: ["EV-PROC-009"],
    metadata: { stage: "SIMULATE", mode: "DRY_RUN" },
  },
  {
    id: "runtime",
    label: "Migration Runtime",
    layer: "L4_RUNTIME",
    type: "SERVICE",
    x: 500,
    y: 390,
    environment: "DEV",
    state: "HEALTHY",
    risk: 10,
    confidence: 100,
    evidenceIds: ["EV-RUN-003"],
    metadata: { port: 8080, execution: "SIMULATED_DEV" },
  },
  {
    id: "a000",
    label: "A000",
    layer: "L5_INTELLIGENCE",
    type: "MASTER_ORCHESTRATOR",
    x: 500,
    y: 120,
    environment: "GLOBAL",
    state: "HEALTHY",
    risk: 4,
    confidence: 100,
    evidenceIds: ["EV-A000-001"],
    metadata: { authority: "GOVERNED", productionWrite: false },
  },
  {
    id: "approval",
    label: "Approval Gate",
    layer: "L6_GOVERNANCE",
    type: "POLICY_GATE",
    x: 820,
    y: 320,
    environment: "DEV",
    state: "HEALTHY",
    risk: 5,
    confidence: 100,
    evidenceIds: ["EV-GOV-007"],
    metadata: { status: "APPROVED", bypass: false },
  },
  {
    id: "risk",
    label: "Mandatory Field Risk",
    layer: "L7_RISK",
    type: "DATA_QUALITY_RISK",
    x: 160,
    y: 455,
    environment: "DEV",
    state: "RISK",
    risk: 78,
    confidence: 97,
    evidenceIds: ["EV-RISK-021"],
    metadata: { severity: "HIGH", affected: "customer_profile" },
  },
  {
    id: "simulation",
    label: "Future-State Simulation",
    layer: "L8_SIMULATION",
    type: "DIGITAL_REHEARSAL",
    x: 820,
    y: 455,
    environment: "DEV",
    state: "PLANNED",
    risk: 12,
    confidence: 96,
    evidenceIds: ["EV-SIM-015"],
    metadata: { targetWrites: 0, cutover: false },
  },
  {
    id: "evidence",
    label: "Evidence Package",
    layer: "L9_EVIDENCE",
    type: "EVIDENCE",
    x: 500,
    y: 525,
    environment: "DEV",
    state: "HEALTHY",
    risk: 2,
    confidence: 100,
    evidenceIds: ["EV-PKG-100"],
    metadata: { sha256: "available", complete: true },
  },
];

const edges: TwinGraphEdge[] = [
  { id: "e1", source: "enterprise", target: "source", type: "CONTAINS", confidence: 100, evidenceIds: ["EV-ENT-001"] },
  { id: "e2", source: "enterprise", target: "api", type: "CONTAINS", confidence: 100, evidenceIds: ["EV-ENT-001"] },
  { id: "e3", source: "a000", target: "process", type: "EXECUTED_BY", confidence: 100, evidenceIds: ["EV-A000-001"] },
  { id: "e4", source: "source", target: "schema", type: "CONTAINS", confidence: 100, evidenceIds: ["EV-DATA-011"] },
  { id: "e5", source: "schema", target: "process", type: "READS_FROM", confidence: 100, evidenceIds: ["EV-PROC-009"] },
  { id: "e6", source: "process", target: "api", type: "CALLS", confidence: 98, evidenceIds: ["EV-API-001"] },
  { id: "e7", source: "process", target: "runtime", type: "EXECUTED_BY", confidence: 100, evidenceIds: ["EV-RUN-003"] },
  { id: "e8", source: "process", target: "approval", type: "GOVERNED_BY", confidence: 100, evidenceIds: ["EV-GOV-007"] },
  { id: "e9", source: "schema", target: "risk", type: "IMPACTS", confidence: 97, evidenceIds: ["EV-RISK-021"] },
  { id: "e10", source: "risk", target: "simulation", type: "PREDICTED_TO_IMPACT", confidence: 96, evidenceIds: ["EV-SIM-015"] },
  { id: "e11", source: "approval", target: "simulation", type: "GOVERNED_BY", confidence: 100, evidenceIds: ["EV-GOV-007"] },
  { id: "e12", source: "simulation", target: "evidence", type: "EVIDENCED_BY", confidence: 100, evidenceIds: ["EV-PKG-100"] },
  { id: "e13", source: "runtime", target: "evidence", type: "EVIDENCED_BY", confidence: 100, evidenceIds: ["EV-PKG-100"] },
];

export function buildEnterpriseTwinGraph(
  temporalState: TwinTemporalState = "CURRENT",
): EnterpriseTwinGraph {
  return {
    generatedAt: new Date().toISOString(),
    temporalState,
    nodes,
    edges,
    safety: {
      readOnly: true,
      productionWriteAllowed: false,
      productionCutoverAllowed: false,
      destructiveActionAllowed: false,
      policyBypassAllowed: false,
    },
  };
}

