from __future__ import annotations
from .models import Capability

# Shared platform capabilities. Database-specific/common capabilities from 012 are imported
# dynamically and deduplicated rather than copied here.
SEED_CAPABILITIES = [
    Capability("KCP90001", "Universal Registry and Crosswalk", "ORCHESTRATION", "Canonical registry for families, agents, capabilities, skills and tools with alias crosswalks", tags=("dedup","registry","crosswalk")),
    Capability("KCP90002", "Intent and Situation Classification", "ORCHESTRATION", "Classify objective, domain, technology, lifecycle stage, risk and required specialist coverage", tags=("intent","routing","situation")),
    Capability("KCP90003", "Policy and Business Rule Runtime", "GOVERNANCE", "Evaluate business rules, environment boundaries, approvals and execution policy", tags=("policy","business rules","governance")),
    Capability("KCP90004", "Execution DAG Planning", "ORCHESTRATION", "Build dependency-aware ordered/parallel execution plans with rollback edges", tags=("dag","dependencies","workflow")),
    Capability("KCP90005", "Governed Tool Gateway", "TOOLS", "Central authorization, invocation and evidence wrapper for deterministic tools", tags=("tools","authorization","evidence")),
    Capability("KCP90006", "Skill Dispatcher", "SKILLS", "Reusable skill selection and invocation without creating unnecessary agents", tags=("skills","dispatch","reuse")),
    Capability("KCP90007", "Independent Validator and Judge Layer", "ASSURANCE", "Independent correctness, safety, reconciliation and evidence validation", tags=("validation","judge","assurance")),
    Capability("KCP90008", "Dynamic Specialist Allocation", "ORCHESTRATION", "Allocate bounded specialists based on domain, technology, stage and risk", tags=("agents","routing","specialist")),
    Capability("KCP90009", "Knowledge Graph and Digital Twin Reasoning", "KNOWLEDGE", "Graph dependency, lineage, impact and enterprise relationship reasoning", tags=("knowledge graph","digital twin","impact")),
    Capability("KCP90010", "Authoritative Live Context Manager", "STATE", "Maintain one current migration/change identity chain and environment state", tags=("context","state","identity")),
    Capability("KCP90011", "Semantic Deduplication", "ORCHESTRATION", "Detect equivalent functionality using IDs, normalized signatures and semantic similarity", tags=("dedup","semantic","reuse")),
    Capability("KCP90012", "Conflict Resolution", "ORCHESTRATION", "Resolve competing agent recommendations using policy, evidence and validators", tags=("conflict","arbitration","evidence")),
    Capability("KCP90013", "Simulation and What-if Analysis", "SIMULATION", "Evaluate change outcomes and blast radius before execution", tags=("simulation","what-if","risk")),
    Capability("KCP90014", "Autonomous Root Cause Analysis", "HEALING", "Rank root causes from evidence, dependencies and temporal signals", tags=("rca","diagnosis","healing")),
    Capability("KCP90015", "Self-Healing Planner", "HEALING", "Generate reversible remediation plans that require simulation, validation and policy approval", tags=("repair","rollback","healing")),
    Capability("KCP90016", "Rollback and Recovery Orchestrator", "RESILIENCE", "Checkpoint, inverse action, restore, failback and post-recovery verification", tags=("rollback","recovery","resilience")),
    Capability("KCP90017", "Data Contract and Drift Governance", "DATA", "Validate contracts, schema compatibility, drift and downstream impact", tags=("data contract","schema drift","compatibility")),
    Capability("KCP90018", "Canonical Database Intermediate Model", "DATABASE", "Vendor-neutral representation of schema, types, constraints, SQL and operational semantics", tags=("database","ir","translation")),
    Capability("KCP90019", "Cross-Database Translation", "DATABASE", "Translate through canonical database IR instead of pairwise duplicated translators", tags=("database","translation","sql dialect")),
    Capability("KCP90020", "Data Quality Rule Compiler", "DATA", "Compile business rules into executable SQL/Python/tool-specific checks", tags=("quality","rules","compiler")),
    Capability("KCP90021", "Reconciliation Runtime", "ASSURANCE", "Compare counts, keys, values, aggregates, relationships and business-rule outcomes", tags=("reconciliation","variance","validation")),
    Capability("KCP90022", "Lineage and Provenance", "EVIDENCE", "Trace requirement/source through transformation, execution, target and evidence", tags=("lineage","provenance","evidence")),
    Capability("KCP90023", "Evidence Manifest Service", "EVIDENCE", "Authoritative evidence packaging with hashes, approvals, versions and decision trace", tags=("evidence","audit","manifest")),
    Capability("KCP90024", "Evaluation Framework", "EVALUATION", "Gold cases, regression suites, tool-use accuracy, abstention and safety metrics", tags=("evaluation","gold","regression")),
    Capability("KCP90025", "Confidence Calibration and Abstention", "EVALUATION", "Calibrated confidence and safe abstention when evidence is insufficient", tags=("confidence","abstention","calibration")),
    Capability("KCP90026", "Model Router", "AI", "Route tasks by capability, privacy, latency, context, cost and policy", tags=("model routing","cost","privacy")),
    Capability("KCP90027", "RAG Freshness and Source Governance", "KNOWLEDGE", "Version, trust, expiry, refresh and citation controls for retrieved knowledge", tags=("rag","freshness","governance")),
    Capability("KCP90028", "Observability and AgentOps", "OPERATIONS", "Correlated traces, metrics, tool/model usage, failures, retries and state transitions", tags=("observability","agentops","telemetry")),
    Capability("KCP90029", "Cost and FinOps Optimization", "OPERATIONS", "Budget and optimize model, tool, storage and runtime cost", tags=("finops","cost","optimization")),
    Capability("KCP90030", "Performance and Capacity Planning", "OPERATIONS", "Baseline workloads, size targets and detect bottlenecks", tags=("performance","capacity","sizing")),
    Capability("KCP90031", "Security and Privacy Decision Layer", "SECURITY", "Secrets, PII, residency, least privilege and policy enforcement", tags=("security","privacy","pii")),
    Capability("KCP90032", "Versioned Compliance Knowledge Packs", "GOVERNANCE", "Jurisdiction/domain controls as versioned knowledge, not hard-coded universal claims", tags=("compliance","knowledge","versioning")),
    Capability("KCP90033", "Connector Capability Matrix", "INTEGRATION", "Declare connector read/write/test/CDC/schema abilities and constraints", tags=("connector","matrix","capability")),
    Capability("KCP90034", "Environment Promotion Engine", "GOVERNANCE", "Evidence-based DEV-to-nonprod-to-production eligibility gates", tags=("promotion","environment","gate")),
    Capability("KCP90035", "Human Approval and Escalation", "GOVERNANCE", "Route decisions to business, security, architecture or operations approvers", tags=("approval","escalation","human")),
    Capability("KCP90036", "Change Set and Patch Governance", "ENGINEERING", "Track change IDs, diffs, tests, rollback and evidence for generated changes", tags=("change","patch","governance")),
    Capability("KCP90037", "Event-Driven Durable Runtime", "RUNTIME", "Long-running workflow state, events, retries and resumable execution", tags=("events","durable","runtime")),
    Capability("KCP90038", "Resilience Chaos and DR Intelligence", "RESILIENCE", "Failure-mode simulation, DR planning, failover and recovery validation", tags=("chaos","dr","resilience")),
    Capability("KCP90039", "Verified Learning Promotion", "LEARNING", "Promote only evidence-backed outcomes into reusable knowledge, tests, skills and policies", tags=("learning","promotion","evidence")),
    Capability("KCP90040", "Regression Protection", "ASSURANCE", "Block reuse/promotion when new learning regresses validated historical scenarios", tags=("regression","learning","quality")),
]
